pipeline{
    agent any
    stages{
        stage('Installing system packages'){
            steps{
                sh 'Jenkins/install-system-packages.sh'
            }
        }
        stage('Installing App requirements'){
            steps{
                sh 'Jenkins/install-app-requirements.sh'
            }
        }
        stage('Running tests'){
            steps{
                withCredentials([string(credentialsId: 'DATABASE_URI', variable: 'DATABASE_URI')]) {
                    sh 'Jenkins/run-tests.sh'
                }
            }
        }

    }
}