pipeline{
    agent any
    environment{
        CREATE_SCHEMA = 'true'
    }
    stages{
        stage('Installing system packages'){
            steps{
                sh 'bash Jenkins/install-system-packages.sh'
            }
        }
        stage('Installing App requirements'){
            steps{
                sh 'bash Jenkins/install-app-requirements.sh'
            }
        }
        stage('Running tests'){
            steps{
                withCredentials([string(credentialsId: 'DATABASE_URI', variable: 'DATABASE_URI')]) {
                    sh 'bash Jenkins/run-tests.sh'
                }
            }
        }

    }
}