pipeline{
    agent any
    environment{
        CREATE_SCHEMA = 'true'
        RUN_APP = 'false'
    }
    stages{
        stage('Installing system packages'){
            steps{
                sh 'bash Jenkins/install_system_packages.sh'
            }
        }
        stage('Installing App requirements'){
            steps{
                sh 'bash Jenkins/install_app_requirements.sh'
            }
        }
        stage('Running tests'){
            steps{
                withCredentials([string(credentialsId: 'DATABASE_URI', variable: 'DATABASE_URI')]) {
                    sh 'bash Jenkins/run_tests.sh'
                }
            }
        }
        stage('Run app'){
            steps{
                script{
                    if (env.RUN_APP == 'true'){
                        sh 'bash jenkins/run_app.sh'
                    }
                }
            }
        }

    }
}